# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: lwillis <lwillis@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/03/05 12:24:00 by lwillis           #+#    #+#              #
#    Updated: 2025/03/17 10:35:03 by lwillis          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	@make -C ./ex00
	@make -C ./ex01
	@make -C ./ex02

clean:
	@make clean -C ./ex00
	@make clean -C ./ex01
	@make clean -C ./ex02
	
fclean:
	@make fclean -C ./ex00
	@make fclean -C ./ex01
	@make fclean -C ./ex02

.PHONY: all clean fclean
